// Generated by CoffeeScript 1.3.3
/**
 Time module
 @author Jacob Carlsson (Halmhatt)
*/

var time;

time = (function() {
  var DAY, HOUR, MINUTE, SECOND, ceil, days, defaults, diff, floor, format, formatObj, hours, label, labels, milliseconds, minutes, my, round, seconds;
  my = {};
  floor = Math.floor;
  round = Math.round;
  ceil = Math.ceil;
  SECOND = 1000;
  MINUTE = SECOND * 60;
  HOUR = MINUTE * 60;
  DAY = HOUR * 24;
  defaults = {
    format: '${0} ${0.label}'
  };
  labels = {
    milliseconds: 'millisecond/milliseconds',
    seconds: 'second/seconds',
    minutes: 'minute/minutes',
    hours: 'hour/hours',
    days: 'day/days'
  };
  diff = function(date1, date2) {
    if (date2 == null) {
      date2 = new Date();
    }
    return date2.getTime() - date1.getTime();
  };
  milliseconds = function(ms) {
    return ms;
  };
  seconds = function(ms) {
    return ms / 1000;
  };
  minutes = function(ms) {
    return seconds(ms) / 60;
  };
  hours = function(ms) {
    return minutes(ms) / 60;
  };
  days = function(ms) {
    return hours(ms) / 24;
  };
  format = function(str, labelName, value) {
    return str.replace('${' + labelName + '}', value);
  };
  label = function(label, num) {
    var labelArr;
    labelArr = labels[label].split('/');
    if (num === 1) {
      return labelArr[0];
    } else {
      return labelArr[1];
    }
  };
  formatTime;

  formatObj = function(diffObj, formatStr) {
    var key, labelStr, _results;
    _results = [];
    for (key in labels) {
      labelStr = labels[key];
      _results.push(format(formatStr, key, label(labelStr)));
    }
    return _results;
  };
  /*
  	 APIs
  */

  my.toObject = function(date1, date2) {
    diff = diff(date1, date2);
    return {
      milliseconds: floor(milliseconds(diff)),
      seconds: floor(seconds(diff)),
      minutes: floor(minutes(diff)),
      hours: floor(hours(diff)),
      days: floor(days(diff))
    };
  };
  my.toRelativeObject = function(date1, date2) {
    diff = diff(date1, date2);
    days = floor(days(diff));
    diff -= days * DAY;
    hours = floor(hours(diff));
    diff -= hours * HOUR;
    minutes = floor(minutes(diff));
    diff -= minutes * MINUTE;
    seconds = floor(seconds(diff));
    diff -= seconds * SECOND;
    return {
      milliseconds: diff,
      seconds: seconds,
      minutes: minutes,
      hours: hours,
      days: days
    };
  };
  my.toString = function(date1, date2, format) {
    var diffObj;
    if (format == null) {
      format = defaults.format;
    }
    diffObj = my.toObject(date1, date2);
    return formatObj(diffObj, format);
  };
  my.toRelativeString = function(date1, date2, format) {
    var diffObj;
    if (format == null) {
      format = defaults.format;
    }
    diffObj = my.toRelativeObject(date1, date2);
    return formatObj(diffObj, format);
  };
  return my;
})();
